apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-image-updater       # leave as-is
  namespace: default                # leave as-is (this is where your deployment is)
rules:
  - apiGroups: [""]                 # core API group
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["apps"]             # apps API group
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch", "patch", "update"]
