pipeline {
    agent any

    environment {
        // Parametrizing the environment variables
        DOCKER_TAG = "${BUILD_NUMBER}"
        IMAGE_NAME = "himani708/fullstack"
        AWS_REGION = "us-east-1"
        SONAR_URL = 'http://43.205.96.198:9000/'  // SonarQube URL
        GIT_REPO_NAME = "argocd-project"
        GIT_USER_NAME = "himani"
    }

    tools {
        jdk 'java-17'
        maven 'maven'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/him-b/argocd-project.git'
            }
        }

        stage('Compile') {
            steps {
                sh "mvn compile"
            }
        }

        stage('Build') {
            steps {
                sh "mvn clean install"
            }
        }

   /*  stage('Static Code Analysis (SonarQube)') {
           steps {
               withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh "mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}"
                }
            }
        }
*/
        stage('Build and Tag Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:${DOCKER_TAG} ."
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhubregistry', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                    }
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                sh "docker push ${IMAGE_NAME}:${DOCKER_TAG}"
            }
        }

      
    }
}
